### ISSUE TITLE
getallheaders() error

### ISSUE THREAD

**Issue by lightlycooked** [lkwdwrd/git-deploy#18]
After following the setup instructions I get the following error in my log: 

**PHP Fatal error:  Call to undefined function getallheaders() in /home/themechef/public_html/deploy/github.php on line 39**

I've looked through all the other files and I don't see any other reference to this function. Any idea why I might be getting this error? 

Thanks in advance.

**Comment by DennisDreissen** [comment]
Which PHP version and webserver are you using? If you're using nginx, try this: http://php.net/manual/en/function.getallheaders.php#84262

**Comment by lightlycooked** [comment]
Apache Version: 2.4.12
PHP Version: 5.3.29

**Comment by DennisDreissen** [comment]
Can you try the custom getallheaders function anyways? I think the build-in getallheaders function is only available from PHP 5.4.0 onwards, if PHP is running under FastCGI.

**Comment by lightlycooked** [comment]
This worked great. I appreciate your help!
