### ISSUE TITLE
Need .ssh directory for httpd/nginx user

### ISSUE THREAD

**Issue by geekmichael** [lkwdwrd/git-deploy#6]
Greetings and thanks for this great program.

I am using Ubuntu 14 with Nginx on my local computer, my project is hosted at Bitbucket. Just now I sorted out .ssh directory must be created manually for user www-data, and copy ssh key files from /root/.ssh directory. If there could be more debug information in log file, that will be very helpful.

**Comment by davo3** [comment]
@geekmichael , could you please provide a few more details about the point you mentioned, I can not figure out the permission of www-data, (I am on Debian 7), with root I can make git pull and it works fine with ssh keys (no password needed) but with www-data (which AFA I understand works during post request from bitbucket) it always gives permission denied. I tried to create ``/www-data/.ssh`` folder as you pointed out, and put my private key in there, but still when I manually do ``sudo -u www-data git pull`` I again get permission denied.

Thanks
